# Generated by Django 4.2.7 on 2024-03-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_activation_log_level_eventstream_log_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="RQQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("available", "available"),
                            ("unavailable", "unavailable"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "core_rq_queue",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RulebookProcessQueue",
            fields=[
                (
                    "process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.rulebookprocess",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulebook_process_queues",
                        to="core.rqqueue",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["queue"], name="core_rulebo_queue_i_6d6e3d_idx"
                    )
                ],
            },
        ),
    ]
