# Generated by Django 4.2.7 on 2024-03-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_activation_log_level_eventstream_log_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="RulebookProcessQueue",
            fields=[
                ("queue_name", models.CharField(max_length=255)),
                (
                    "process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.rulebookprocess",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["queue_name"],
                        name="core_rulebo_queue_n_b7b007_idx",
                    )
                ],
            },
        ),
    ]
