# Generated by Django 4.2.7 on 2024-03-15 19:54
import django.db.models.deletion
from django.db import migrations, models

import aap_eda.core.enums


def populate_rulebook_process_queue(apps, schema_editor):
    RQQueue = apps.get_model("core", "RQQueue")  # noqa: N806
    RulebookProcessQueue = apps.get_model(  # noqa: N806
        "core",
        "RulebookProcessQueue",
    )
    RulebookProcess = apps.get_model("core", "RulebookProcess")  # noqa: N806
    if not RQQueue.objects.filter(name="activation").exists():
        RQQueue.objects.create(
            name="activation",
            state="available",
        )
    queue = RQQueue.objects.get(name="activation")
    for running_process in RulebookProcess.objects.filter(
        status="RUNNING",
    ).all():
        RulebookProcessQueue.objects.create(
            queue=queue,
            process=running_process,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_activation_log_level_eventstream_log_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="status",
            field=models.TextField(
                choices=[
                    ("starting", "starting"),
                    ("running", "running"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                    ("stopping", "stopping"),
                    ("stopped", "stopped"),
                    ("deleting", "deleting"),
                    ("completed", "completed"),
                    ("unresponsive", "unresponsive"),
                    ("error", "error"),
                    ("unknown", "unknown"),
                ],
                default=aap_eda.core.enums.ActivationStatus["PENDING"],
            ),
        ),
        migrations.AlterField(
            model_name="eventstream",
            name="status",
            field=models.TextField(
                choices=[
                    ("starting", "starting"),
                    ("running", "running"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                    ("stopping", "stopping"),
                    ("stopped", "stopped"),
                    ("deleting", "deleting"),
                    ("completed", "completed"),
                    ("unresponsive", "unresponsive"),
                    ("error", "error"),
                    ("unknown", "unknown"),
                ],
                default=aap_eda.core.enums.ActivationStatus["PENDING"],
            ),
        ),
        migrations.AlterField(
            model_name="rulebookprocess",
            name="status",
            field=models.TextField(
                choices=[
                    ("starting", "starting"),
                    ("running", "running"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                    ("stopping", "stopping"),
                    ("stopped", "stopped"),
                    ("deleting", "deleting"),
                    ("completed", "completed"),
                    ("unresponsive", "unresponsive"),
                    ("error", "error"),
                    ("unknown", "unknown"),
                ],
                default=aap_eda.core.enums.ActivationStatus["PENDING"],
            ),
        ),
        migrations.CreateModel(
            name="RQQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("available", "available"),
                            ("unavailable", "unavailable"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "core_rq_queue",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RulebookProcessQueue",
            fields=[
                (
                    "process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.rulebookprocess",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulebook_process_queues",
                        to="core.rqqueue",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["queue"], name="core_rulebo_queue_i_6d6e3d_idx"
                    )
                ],
            },
        ),
        migrations.RunPython(
            populate_rulebook_process_queue,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
